PREAMBLE
/////////////////////////////////////////////////////////////////////////
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING
//
//  DO NOT EDIT THIS FILE!
//  Loading an edited TLA file in the TLA 700 application can
//  cause the application to crash.  Editing this file can not
//  only introduce errors in the text portion of the file but
//  most editors (e.g. Notepad) will silently corrupt the binary
//  data portion of the file, causing the TLA 700 application to
//  crash when the corrupted file is loaded by the application.
//
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING
//  WARNING   WARNING   WARNING   WARNING   WARNING   WARNING   WARNING
//
/////////////////////////////////////////////////////////////////////////
CafcCompositeCell "Preamble" "$$" {
	CafcStringCell "UserComment" "$$" = { "LPC Support Package Instrument Setup"  }
	CafcByteCell "FileType" "$$" = { 1  }
	CafcArrayCell "InstrumentAfcNames" "$$" {
		CafcStringCell "NoName" "$$" = { "LPC"  }
	}
	CafcArrayCell "InstrumentUserNames" "$$" {
		CafcStringCell "NoName" "$$" = { "LPC"  }
	}
	CafcArrayCell "ModuleFilterNames" "$$" {
		CafcStringCell "NoName" "$$" = { "LPC - Filter"  }
	}
	CafcArrayCell "InstrumentSamples" "$$" {
		CafcLongCell "NoName" "$$" = { -1  }
	}
	CafcArrayCell "InstrumentExistingSamples" "$$" {
		CafcLongCell "NoName" "$$" = { -1  }
	}
	CafcArrayCell "InstrumentTypes" "$$" {
		CafcByteCell "NoName" "$$" = { 20  }
	}
	CafcStringCell "ProductVersionNoString" "$$" = { "5.7.46.0"  }
}
CapRoot "Root" "$$" {
	CjmInstrument "LPC" "$LPC$" {
		CafcLongLongCell "SysTrigTime" "$$" = { 692722793375  }
		CafcLongLongCell "SysExpOffsetTime" "$$" = { 0  }
		CafcStringCell "UserName" "$$" = { "LPC"  }
		CafcLongLongCell "TimeSkew" "$$" = { 0  }
		CcmSaveDataCompositeCell "TbTimebaseSet" "$$" {
			CjmTimebaseData "TbMainTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 256  }
				CafcLongCell "DaBytesPerSample" "$$" = { 26  }
				CafcByteCell "DaFinalState" "$$" = { 1  }
				CafcBooleanCell "DaTrigPresent" "$$" = { TRUE  }
				CafcLongCell "DaTrigSample" "$$" = { 127  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 692722793375  }
				CafcByteCell "DaTrigType" "$$" = { 1  }
				CafcBooleanCell "DaTrigAll" "$$" = { TRUE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 692720884500  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 692724718125  }
				CafcLongCell "DaStartDate" "$$" = { 1293567614  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 125  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 1000  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { FALSE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { TRUE  }
				}
				CcmDataSet "DaSetViolation" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
				CafcByteCell "jmCtmr1Mode" "$$" = { 0  }
				CafcLongLongCell "jmCtmr1Value" "$$" = { 0  }
				CafcByteCell "jmCtmr2Mode" "$$" = { 0  }
				CafcLongLongCell "jmCtmr2Value" "$$" = { 0  }
				CafcLongLongCell "jmCurSyncSpeed" "$$" = { 120000000  }
				CafcByteCell "jmStatusBitType" "$$" = { 3  }
				CafcByteCell "jmClkMode" "$$" = { 1  }
				CafcLongCell "jmTimestampReplicant" "$$" = { 0  }
				CafcLongLongCell "jmTimestampOffset" "$$" = { 1000  }
				CafcBooleanCell "jmDemuxClkQual" "$$" = { TRUE  }
				CafcByteCell "jmSanitizeMode" "$$" = { 0  }
				CjmCompareData "CmpData" "$$" {
					CafcBooleanCell "CmpEnable" "$$" = { FALSE  }
					CafcBooleanCell "CmpRuntimeEnable" "$$" = { FALSE  }
					CafcByteCell "CmpRuntimeCond" "$$" = { 0  }
					CcmSavedInstRef "CmpRefSource" "$$" {
						CafcStringCell "SavedInstRef" "$$" = { "LPC"  }
					}
					CafcBooleanCell "CmpAllData" "$$" = { TRUE  }
					CafcByteCell "CmpStartRef" "$$" = { 2  }
					CafcLongCell "CmpStartSample" "$$" = { 0  }
					CafcLongCell "CmpCount" "$$" = { 0  }
					CafcByteCell "CmpAlignRef" "$$" = { 1  }
					CafcLongCell "CmpAlignOffset" "$$" = { 0  }
				}
				CafcArrayCell "CmpSuppression" "$$" {
				}
				CafcByteCell "CmpSupOpMode" "$$" = { 0  }
				CafcLongLongCell "CmpSupOpCount" "$$" = { 1024  }
				CafcBooleanCell "CmpSupTrigRelative" "$$" = { TRUE  }
				CafcBooleanCell "smSaveSystemType" "$$" = { FALSE  }
				CafcLongCell "JmXFactor" "$$" = { 1  }
				CafcLongCell "JmDataExpansionFactor" "$$" = { 1  }
				CafcBooleanCell "JmXIsWideStorage" "$$" = { FALSE  }
				CafcBooleanCell "JmHasGapCounters" "$$" = { FALSE  }
			}
			CjmTimebaseData "TbHiResTimebaseData" "$$" {
				CafcLongCell "DaNumSamples" "$$" = { 16320  }
				CafcLongCell "DaBytesPerSample" "$$" = { 17  }
				CafcByteCell "DaFinalState" "$$" = { 1  }
				CafcBooleanCell "DaTrigPresent" "$$" = { TRUE  }
				CafcLongCell "DaTrigSample" "$$" = { 8204  }
				CafcLongLongCell "DaTrigSampleTime" "$$" = { 692722793375  }
				CafcByteCell "DaTrigType" "$$" = { 1  }
				CafcBooleanCell "DaTrigAll" "$$" = { TRUE  }
				CafcLongLongCell "DaFirstSampleTime" "$$" = { 692721767875  }
				CafcLongLongCell "DaLastSampleTime" "$$" = { 692723807750  }
				CafcLongCell "DaStartDate" "$$" = { 1293567614  }
				CafcLongLongCell "DaTimeStampTick" "$$" = { 125  }
				CafcLongLongCell "DaSamplePeriod" "$$" = { 125  }
				CafcBooleanCell "DaAsyncDataClock" "$$" = { TRUE  }
				CcmDataSet "DaSetNormal" "$$" {
					CafcBooleanCell "DaValid" "$$" = { TRUE  }
				}
				CafcLongCell "JmXFactor" "$$" = { 1  }
				CafcLongCell "JmDataExpansionFactor" "$$" = { 1  }
				CafcBooleanCell "JmXIsWideStorage" "$$" = { FALSE  }
				CafcBooleanCell "JmHasGapCounters" "$$" = { FALSE  }
				CcmDataSet "DaSetViolation" "$$" {
					CafcBooleanCell "DaValid" "$$" = { FALSE  }
				}
			}
		}
		CjmConfig "CommonConfigModel" "$$" {
			CafcLongCell "CoNumModules" "$$" = { 1  }
			CafcLongCell "CoNumChannels" "$$" = { 136  }
			CafcLongLongCell "CoMaxSyncRate" "$$" = { 450000000  }
			CafcLongLongCell "CoMaxSampleRate" "$$" = { 2000  }
			CafcLongCell "CoMaxDepth" "$$" = { 33554432  }
			CafcBooleanCell "CoEnabled" "$$" = { TRUE  }
			CafcLongLongCell "CoStzOffset" "$$" = { 0  }
			CafcLongCell "jmConfigMasterWidth" "$$" = { 136  }
			CafcLongCell "jmConfigSlaveWidth" "$$" = { 0  }
			CafcLongCell "jmConfigSlave2Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave3Width" "$$" = { 0  }
			CafcLongCell "jmConfigSlave4Width" "$$" = { 0  }
			CafcByteCell "jmSeries" "$$" = { 2  }
			CafcLongLongCell "jmMagnivuPeriod" "$$" = { 125  }
			CafcLongCell "jmMagnivuDepth" "$$" = { 16384  }
			CafcLongCell "jmWordRecDataSize" "$$" = { 17  }
			CafcLongCell "jmWordRecStatusSize" "$$" = { 1  }
			CafcArrayCell "jmDisplayStatusBitList" "$$" {
				CafcByteCell "NoName" "$$" = { 3  }
				CafcByteCell "NoName" "$$" = { 4  }
				CafcByteCell "NoName" "$$" = { 5  }
			}
			CafcArrayCell "jmTriggerStatusBitList" "$$" {
				CafcByteCell "NoName" "$$" = { 3  }
			}
			CafcBooleanCell "jmCustomRestoreFlag" "$$" = { FALSE  }
		}
		CjmScreenParam "jmScreenParams" "$$" {
			CcmToolbarParamSet "cmToolbarParamSet" "$$" {
				CafcBooleanCell "cmToolbarParamSetUseDefault" "$$" = { FALSE  }
				CcmToolbarParams "jsFileBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { -2  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jsSetupBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 99  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
			}
			CafcLongCell "FrameWidth" "$$" = { 734  }
			CafcLongCell "FrameHeight" "$$" = { 542  }
			CafcLongCell "FrameXPos" "$$" = { 110  }
			CafcLongCell "FrameYPos" "$$" = { 110  }
			CafcByteCell "ShowState" "$$" = { 1  }
			CafcByteCell "jmSParamSetupChannelsVisible" "$$" = { 1  }
			CafcByteCell "jmSParamSetupShowGroups" "$$" = { 0  }
		}
		CcmWindowParams "jmTrigScreenParams" "$$" {
			CcmToolbarParamSet "cmToolbarParamSet" "$$" {
				CafcBooleanCell "cmToolbarParamSetUseDefault" "$$" = { FALSE  }
				CcmToolbarParams "jtFileBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { -2  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jtAddStateBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 78  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jtEditBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 135  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jtStorageBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 215  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jtTrigPosBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { 475  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 0  }
				}
				CcmToolbarParams "jtMagniVuBarParams" "$$" {
					CafcBooleanCell "cmToolbarParamIsVisible" "$$" = { TRUE  }
					CafcBooleanCell "cmToolbarParamIsFloating" "$$" = { FALSE  }
					CafcLongCell "cmToolbarParamDockSide" "$$" = { 59419  }
					CafcLongCell "cmToolbarParamXPos" "$$" = { -2  }
					CafcLongCell "cmToolbarParamYPos" "$$" = { 24  }
				}
			}
			CafcLongCell "FrameWidth" "$$" = { 640  }
			CafcLongCell "FrameHeight" "$$" = { 450  }
			CafcLongCell "FrameXPos" "$$" = { 20  }
			CafcLongCell "FrameYPos" "$$" = { 20  }
			CafcByteCell "ShowState" "$$" = { 1  }
		}
		CjmJupiterChannelInfo "CiChannelInfo" "$$" {
			CjmChannelArray "CiChannels" "$$" {
				CjmChannel "A1_3" "$LSMI#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LSMI#"  }
				}
				CjmChannel "A1_2" "$LPCPD#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LPCPD#"  }
				}
				CjmChannel "A1_1" "$LPME#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LPME#"  }
				}
				CjmChannel "A1_0" "$CLKRUN#$" {
					CafcStringCell "jmAsyncName" "$$" = { "CLKRUN#"  }
				}
				CjmChannel "A0_7" "$SERIRQ$" {
					CafcStringCell "jmAsyncName" "$$" = { "SERIRQ"  }
				}
				CjmChannel "A0_6" "$LDRQ#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LDRQ#"  }
				}
				CjmChannel "A0_5" "$LRESET#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LRESET#"  }
				}
				CjmChannel "A0_4" "$LFRAME#$" {
					CafcStringCell "jmAsyncName" "$$" = { "LFRAME#"  }
				}
				CjmChannel "A0_3" "$LAD3$" {
					CafcStringCell "jmAsyncName" "$$" = { "LAD3"  }
				}
				CjmChannel "A0_2" "$LAD2$" {
					CafcStringCell "jmAsyncName" "$$" = { "LAD2"  }
				}
				CjmChannel "A0_1" "$LAD1$" {
					CafcStringCell "jmAsyncName" "$$" = { "LAD1"  }
				}
				CjmChannel "A0_0" "$LAD0$" {
					CafcStringCell "jmAsyncName" "$$" = { "LAD0"  }
				}
				CjmChannel "CK1" "$LCLK$" {
					CafcStringCell "jmAsyncName" "$$" = { "LCLK"  }
				}
			}
			CafcBooleanCell "jmInitAsyncForCustom" "$$" = { FALSE  }
			CjmProbeSet "jmProbeSet" "$$" {
				CafcLongLongCell "jmDefaultThreshold" "$$" = { 1500000000000  }
			}
			CjmUserGroups "jmUserGroups" "$$" {
				CjmChannelGroup "1UserGrp" "$CTRL$" {
					CafcStringCell "UserName" "$$" = { "CTRL"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { FALSE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "LCLK,LRESET#,LFRAME#,LDRQ#,SERIRQ,CLKRUN#,LPME#,LPCPD#,LSMI#"  }
				}
				CjmChannelGroup "2UserGrp" "$DATA$" {
					CafcStringCell "UserName" "$$" = { "DATA"  }
					CafcBooleanCell "ClaAMSgenerated" "$$" = { FALSE  }
					CafcBooleanCell "ClaAMSonOff" "$$" = { TRUE  }
					CafcByteCell "ClaAMSradix" "$$" = { 0  }
					CafcStringCell "ClaAMSsymFileName" "$$" = { ""  }
					CafcBooleanCell "ClaAppGenerated" "$$" = { FALSE  }
					CafcStringCell "ClaGroupDefinition" "$$" = { "LAD3,LAD2,LAD1,LAD0"  }
				}
			}
			CjmAnalogMux "jmAnalogMux" "$$" {
				CafcCompositeCell "m0c0" "$$" {
					CafcStringCell "jmFeedName" "$$" = { "CK0"  }
					CafcLongLongCell "jmFeedDelay" "$$" = { -45  }
					CafcLongCell "jmFeedAttenuation" "$$" = { 10  }
				}
				CafcCompositeCell "m0c1" "$$" {
					CafcStringCell "jmFeedName" "$$" = { "A3_7"  }
					CafcLongLongCell "jmFeedDelay" "$$" = { -263  }
					CafcLongCell "jmFeedAttenuation" "$$" = { 10  }
				}
				CafcCompositeCell "m0c2" "$$" {
					CafcStringCell "jmFeedName" "$$" = { "A3_6"  }
					CafcLongLongCell "jmFeedDelay" "$$" = { 42  }
					CafcLongCell "jmFeedAttenuation" "$$" = { 10  }
				}
				CafcCompositeCell "m0c3" "$$" {
					CafcStringCell "jmFeedName" "$$" = { "A3_5"  }
					CafcLongLongCell "jmFeedDelay" "$$" = { -328  }
					CafcLongCell "jmFeedAttenuation" "$$" = { 10  }
				}
			}
		}
		CcmSupportedLA "SupportedLA" "$$" {
			CafcStringCell "PackageName" "$$" = { "LPC"  }
			RDAInternalOpMarkSet "RDAOpMarkSet" "$$" {
			}
		}

         CjmClock "jmClk" "$$" { 
             CafcByteCell "jmClkMode" "$$" = { 2  0 255 }
             CafcLongLongCell "jmClkIntRate" "$$" = { 4000 4000 50000000000 1 AFC_FIXED_INCR  }
             CjmExternalClock "jmClkGPSyncClk" "$$" { 
                 CafcByteCell "jmClkGPSyncClkMode" "$$" = { 0  0 255 }
                 CjmClockDefinition "jmClkGPSyncBasicClk" "$$" { 
                     CafcArrayCell "jmClkGPSyncDef" "$$" { 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "CK1" "$$" = { 0  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                     } 
                 } 
                 CjmClockDefinition "jmClkGPSyncAdv1Clk" "$$" { 
                     CafcArrayCell "jmClkGPSyncDef" "$$" { 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "CK1" "$$" = { 0  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                     } 
                 } 
                 CjmClockDefinition "jmClkGPSyncAdv2Clk" "$$" { 
                     CafcArrayCell "jmClkGPSyncDef" "$$" { 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                         CafcArrayCell "" "$$" { 
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                             CafcByteCell "" "$$" = { 4  0 255 }
                         } 
                     } 
                 } 
                 CjmExternalPresets "jmClkGPBasicPresets" "$$" { 
                     CafcLongCell "jmClkDefHold" "$$" = { 0  }
                     CafcLongCell "jmClkDefLogin" "$$" = { 1  }
                     CafcLongLongCell "jmClkDefAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                     CafcBooleanCell "jmClkGrpDemux" "$$" = { FALSE  }
                     CafcArrayCell "jmClkGrpPresets" "$$" { 
                         CjmGroupPreset "" "$CTRL$" { 
                             CafcStringCell "UserName" "$$" = { "CTRL"  }
                             CafcLongCell "jmClkGrpHold" "$$" = { 0  }
                             CafcBooleanCell "jmClkDefHold" "$$" = { TRUE  }
                             CafcLongCell "jmClkGrpLogin" "$$" = { 1  }
                             CafcBooleanCell "jmClkDefLogin" "$$" = { TRUE  }
                             CafcLongLongCell "jmClkGrpAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                             CafcBooleanCell "jmClkDefAlignment" "$$" = { TRUE  }
                         } 
                         CjmGroupPreset "" "$DATA$" { 
                             CafcStringCell "UserName" "$$" = { "DATA"  }
                             CafcLongCell "jmClkGrpHold" "$$" = { 0  }
                             CafcBooleanCell "jmClkDefHold" "$$" = { TRUE  }
                             CafcLongCell "jmClkGrpLogin" "$$" = { 1  }
                             CafcBooleanCell "jmClkDefLogin" "$$" = { TRUE  }
                             CafcLongLongCell "jmClkGrpAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                             CafcBooleanCell "jmClkDefAlignment" "$$" = { TRUE  }
                         } 
                     } 
                 } 
                 CjmExternalPresets "jmClkGPAdvPresets" "$$" { 
                     CafcLongCell "jmClkDefHold" "$$" = { 0  }
                     CafcLongCell "jmClkDefLogin" "$$" = { 1  }
                     CafcLongLongCell "jmClkDefAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                     CafcBooleanCell "jmClkGrpDemux" "$$" = { FALSE  }
                     CafcArrayCell "jmClkGrpPresets" "$$" { 
                         CjmGroupPreset "" "$CTRL$" { 
                             CafcStringCell "UserName" "$$" = { "CTRL"  }
                             CafcLongCell "jmClkGrpHold" "$$" = { 0  }
                             CafcBooleanCell "jmClkDefHold" "$$" = { TRUE  }
                             CafcLongCell "jmClkGrpLogin" "$$" = { 1  }
                             CafcBooleanCell "jmClkDefLogin" "$$" = { TRUE  }
                             CafcLongLongCell "jmClkGrpAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                             CafcBooleanCell "jmClkDefAlignment" "$$" = { TRUE  }
                         } 
                         CjmGroupPreset "" "$DATA$" { 
                             CafcStringCell "UserName" "$$" = { "DATA"  }
                             CafcLongCell "jmClkGrpHold" "$$" = { 0  }
                             CafcBooleanCell "jmClkDefHold" "$$" = { TRUE  }
                             CafcLongCell "jmClkGrpLogin" "$$" = { 1  }
                             CafcBooleanCell "jmClkDefLogin" "$$" = { TRUE  }
                             CafcLongLongCell "jmClkGrpAlignment" "$$" = { 2000 -7000 8500 500 AFC_FIXED_INCR  }
                             CafcBooleanCell "jmClkDefAlignment" "$$" = { TRUE  }
                         } 
                     } 
                 } 
             } 
         }

		CjmTriggerInfo "jmTriggerInfo" "$$" {
			CjmTrigger "jmTriggerAsyncSync" "$$" {
				CcmSymbolFileLinks "SymbolFileLinks" "$$" {
				}
				CjmWordDefinitions "jmTrigWordDefinitions" "$$" {
				}
				CjmTransitionDefinitions "jmTrigTransitionDefinitions" "$$" {
				}
				CjmSnapshotDefinitions "jmTrigSnapshotDefinitions" "$$" {
				}
				CjmEventMacros "jmTrigEventMacros" "$$" {
					CjmEventMacro "jmEventMacro" "$ $" {
						CafcStringCell "jmMacroUserName" "$$" = { " "  }
						CafcStringCell "jmMacroString" "$$" = { "( Anything )"  }
						CafcByteCell "jmMacroDisplayMode" "$$" = { 1  }
					}
				}
				CjmStorage "jmStorage" "$$" {
					CafcByteCell "jmStorageAcqMode" "$$" = { 0  }
					CafcByteCell "jmStorageMode" "$$" = { 0  }
					CafcByteCell "jmStartStop" "$$" = { 0  }
					CafcByteCell "jmTriggerDelay" "$$" = { 50  }
					CafcByteCell "jmHiResDelay" "$$" = { 50  }
					CafcLongLongCell "jmStorageUserDepth" "$$" = { 256  }
					CafcLongLongCell "jmStorageHiResDepth" "$$" = { 16320  }
					CafcBooleanCell "jmStorageForceMainPrefill" "$$" = { FALSE  }
					CafcLongLongCell "jmStorageHiResStoreRate" "$$" = { 125  }
					CjmStorageClause "jmStorageClause" "$$" {
						CafcStringCell "jmClauseUiCondition" "$$" = { "( Anything )"  }
						CafcStringCell "jmClauseAction" "$$" = { "( StoreSample )"  }
						CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
					}
				}
				CjmTriggerMachine "jmTriggerMachine" "$$" {
					CafcLongCell "jmTriggerStateCount" "$$" = { 1  }
					CjmTriggerStateArray "jmTriggerStateArray" "$$" {
						CjmTriggerState "jmTriggerState1" "$$" {
							CafcLongCell "jmTriggerClauseCount" "$$" = { 1  }
							CjmTriggerClauseArray "jmTriggerClauseArray" "$$" {
								CjmTriggerClause "jmTriggerClause1" "$$" {
									CafcStringCell "jmClauseUiCondition" "$$" = { "( Channel \"A0(4):U:LFRAME#\" Goes Low ) And ( Channel \"A0(5):U:LRESET#\" = High )"  }
									CafcStringCell "jmClauseAction" "$$" = { "( TriggerAll )"  }
									CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
								}
							}
							CafcStringCell "jmTrigStateComment" "$$" = { "Trigger on the very first sample"  }
						}
					}
				}
				CjmTriggerChannels "jmTriggerChannels" "$$" {
				}
				CjmTriggerGroups "jmTriggerGroups" "$$" {
				}
				CafcByteCell "jmTabSplitWndPage" "$$" = { 1  }
				CafcBooleanCell "jmCommentsVisibleFlag" "$$" = { TRUE  }
				CafcStringCell "jmTrigOwnerID" "$$" = { "PT:LA 1"  }
				CafcBooleanCell "jmTrigToolbarVisibleFlag" "$$" = { TRUE  }
			}

			CjmTrigger "jmTriggerCustom" "$$" {
				CcmSymbolFileLinks "SymbolFileLinks" "$$" {
				}
				CjmWordDefinitions "jmTrigWordDefinitions" "$$" {
				}
				CjmTransitionDefinitions "jmTrigTransitionDefinitions" "$$" {
				}
				CjmSnapshotDefinitions "jmTrigSnapshotDefinitions" "$$" {
				}
				CjmEventMacros "jmTrigEventMacros" "$$" {
				}
				CjmStorage "jmStorage" "$$" {
					CafcByteCell "jmStorageAcqMode" "$$" = { 0  }
					CafcByteCell "jmStorageMode" "$$" = { 0  }
					CafcByteCell "jmStartStop" "$$" = { 0  }
					CafcByteCell "jmTriggerDelay" "$$" = { 50  }
					CafcByteCell "jmHiResDelay" "$$" = { 50  }
					CafcLongLongCell "jmStorageUserDepth" "$$" = { 0  }
					CafcLongLongCell "jmStorageHiResDepth" "$$" = { 0  }
					CafcBooleanCell "jmStorageForceMainPrefill" "$$" = { FALSE  }
					CafcLongLongCell "jmStorageHiResStoreRate" "$$" = { 0  }
					CjmStorageClause "jmStorageClause" "$$" {
						CafcStringCell "jmClauseUiCondition" "$$" = { "( Anything )"  }
						CafcStringCell "jmClauseAction" "$$" = { "( StoreSample )"  }
						CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
					}
				}
				CjmTriggerMachine "jmTriggerMachine" "$$" {
					CafcLongCell "jmTriggerStateCount" "$$" = { 1  }
					CjmTriggerStateArray "jmTriggerStateArray" "$$" {
						CjmTriggerState "jmTriggerState1" "$$" {
							CafcLongCell "jmTriggerClauseCount" "$$" = { 1  }
							CjmTriggerClauseArray "jmTriggerClauseArray" "$$" {
								CjmTriggerClause "jmTriggerClause1" "$$" {
									CafcStringCell "jmClauseUiCondition" "$$" = { "( Anything )"  }
									CafcStringCell "jmClauseAction" "$$" = { "( TriggerSelf )"  }
									CafcStringCell "jmTrigClauseComment" "$$" = { ""  }
								}
							}
							CafcStringCell "jmTrigStateComment" "$$" = { ""  }
						}
					}
				}
				CjmTriggerChannels "jmTriggerChannels" "$$" {
				}
				CjmTriggerGroups "jmTriggerGroups" "$$" {
				}
				CafcByteCell "jmTabSplitWndPage" "$$" = { 0  }
				CafcBooleanCell "jmCommentsVisibleFlag" "$$" = { TRUE  }
				CafcStringCell "jmTrigOwnerID" "$$" = { "ET:LA 1"  }
			}

		}
		CcmFilters "Filters" "$$" {
			CcmFilter "Filter" "$Filter$" {
				CafcStringCell "UserName" "$$" = { "Filter"  }
				CafcStringCell "Description" "$$" = { ""  }
				CafcBooleanCell "FilterEnable" "$$" = { TRUE  }
				CcmFilterClauseDefs "FilterClauses" "$$" {
					CcmFilterClause "FilterClause" "$$" {
						CafcStringCell "UserName" "$$" = { ""  }
						CafcByteCell "FilterClauseType" "$$" = { 0  }
						CafcBooleanCell "FilterClauseDisable" "$$" = { FALSE  }
						CafcStringCell "GroupName" "$$" = { ""  }
						CafcLongCell "FilterForegroundColor" "$$" = { 0  }
						CafcLongCell "FilterBackgroundColor" "$$" = { 15658671  }
						CafcBooleanCell "FilterForegroundDisable" "$$" = { FALSE  }
						CafcBooleanCell "FilterBackgroundDisable" "$$" = { FALSE  }
						CcmFilterEventDefs "FilterEvents" "$$" {
							CcmFSEventLAGroup "FilterEvent" "$$" {
								CafcByteCell "SearchEventType" "$$" = { 0  }
								CafcBooleanCell "SearchEventBoolean" "$$" = { FALSE  }
								CafcStringCell "SearchElement" "$$" = { "DATA"  }
								CafcByteCell "SearchCondition" "$$" = { 0  }
								CafcStringCell "SearchArgument1" "$$" = { "XXXX"  }
								CafcStringCell "SearchArgument2" "$$" = { ""  }
								CafcLongCell "SearchDisasmCondition" "$$" = { 0  }
								CafcBooleanCell "SearchMatchCase" "$$" = { TRUE  }
								CafcByteCell "Radix" "$$" = { 2  }
							}
						}
					}
				}
			}
		}
	}
}
